### ISSUE TITLE
TF Random Bucket Name

### ISSUE THREAD

**Issue by yaya2devops** [yaya2devops/terraform-beginner-bootcamp-2023#13]
### Task 1: Explore the Terraform Registry
- [x] Familiarize yourself with the Terraform Registry, an online repository for Terraform modules and providers. It contains a wide range of resources that can be used to provision infrastructure.

### Task 2: Install the Terraform Random Provider
- [x] Install the Terraform Random Provider, which is a useful Terraform provider for generating random values. It can be used to create random names, numbers, and other dynamic inputs in your infrastructure code.

### Task 3: Run 'terraform init'
- [x] Execute the 'terraform init' command in your Terraform project. This command initializes your working directory and prepares it for creating and managing infrastructure resources.

### Task 4: Generate a Random Bucket Name
- [x] Generate a random name for a bucket using the Terraform Random Provider. This step will create a unique identifier that can be used for your infrastructure resources, such as a storage bucket.

### Task 5: Output the Random Bucket Name
- [x] Display the randomly generated bucket name as an output. This will make the generated name accessible for other parts of your Terraform configuration or for reference in your infrastructure provisioning process.
