### ISSUE TITLE
The Week Zero Perfecting Checklist

### ISSUE THREAD

**Issue by yaya2devops** [yaya2devops/terraform-beginner-bootcamp-2023#27]
I considered to instruct each tech we came across branch-related rather than lumping all in one junk.

|💡|Developer will get enlighten on branch-click of interest.|
|---|:---|
- [x] Task 1: Branch 1 - Semantic remake and Highlight the before Week 0 (Week  Prep)
- [x] Task 2: Branch 5 - Rectify the typo in Dotenv.
- [x] Task 3: Branch 15 - Eliminate the unnecessary "etc" from `json`.
- [x] Task 4: Branch 18 - Add proper asset the `apply` section .
- [x] Task 5: Branch 21 - Resolve issues related to hyperlinks and secrets showup.
- [x] Task 6: Branch 24 - Rename the alias file to the one I executed `./bin/tf_alias`
- [x] Task 6: Branch 24 - Add my own notes `0.9.0` for community.
- [x] Task 7 : Create An All In one Week 0 in `/journal` directory. (Anyway)
- [x] Task 8 : Create a Complete ToC for all Week Zero
- [x] Task 9 : Prepare An All In one Week 1 in `/journal` directory. (Anyway)

You can also consult all of [pre week towards zero combined here.](https://github.com/yaya2devops/terraform-beginner-bootcamp-2023/blob/main/journal/week0.md)

> https://github.com/yaya2devops/terraform-beginner-bootcamp-2023/issues/47 https://github.com/yaya2devops/terraform-beginner-bootcamp-2023/issues/67

**Comment by yaya2devops** [comment]
```
git checkout 27-week-zero-perfecting

# Merge changes from the specified branches, automatically resolving conflicts in favor of the incoming changes
git merge -s recursive -X theirs --no-edit origin/1-semantic-versioning
git merge -s recursive -X theirs --no-edit origin/5-project-root-environment-variable
git merge -s recursive -X theirs --no-edit origin/15-terraform-simple-s3-bucket
git merge -s recursive -X theirs --no-edit origin/18-migrate-terraform-cloud
git merge -s recursive -X theirs --no-edit origin/21-generate-tfrc
git merge -s recursive -X theirs --no-edit origin/24-tf-alias-terraform
```

**Comment by yaya2devops** [comment]
Related: https://github.com/yaya2devops/terraform-beginner-bootcamp-2023/commit/7879ce308dbae5611977751963f2404d52eec21e
