### ISSUE TITLE
The Week One Perfecting Checklist

### ISSUE THREAD

**Issue by yaya2devops** [yaya2devops/terraform-beginner-bootcamp-2023#47]
As [previously implemented](https://github.com/yaya2devops/terraform-beginner-bootcamp-2023/issues/27), we are keeping at it this week. 

This checklist is intended to perfect the tasks and changes made in week one. 
The goal is to review each branch, address any issues, and merge the changes into this union branch.

1. [x] **Task 1: Branch 29 Design Root Module**
   - [x] Fix import tag to 1.2.0
   - [x] Add a toml link
   - [x] Adjust example to have proper sample/bullet points spacing

2. [x] **Task 2: Branch 31 Terraform Configuration Drifts**
   - [x] Move the table to the right
   - [x] Move the second table to the left lamp
   - [x] Update 'YayaToDevOps' to '2'

3. [x] **Task 3: Branch 33 AWS Terrahouse Module**
   - [x] Change 'tree' to 'file' (not folder)
   - [x] Consolidate duplication under refactor
   - [x] Handle 'var' and make it 3 bullets

4. [x] **Task 4: Branch 35 S3 Static Website Hosting Via Terraform**
   - [x] Change 'alone' to 'along'
   - [x] Add a note about adding 'danger' to ensure functionality
   - [x] Detect File Check highlight

5. [x] **Task 5: Branch 37 Cloudfront CDN Implementation**
   - [x] Update the table emoji
   - [x] Correct 'Error 2' and change the description to 'it is downloading instead.'
   - [x] Add another table emoji
   - [x] Add another emoji table

6. [x] **Task 6: Branch 43 Assets Upload Via Terraform**
   - [x] Add website URL in front of 'elizabeth'

7. [x] **Task 7: General**
   - [x] Look into the 'assets' folder for every version and consider adding any missing files or elements.

## Fulfillment
 - [x] Add Validator Assets For Week One.
 - [x] Provide Evidence of why Validator Failed 10+ trials.
 - [x] Add the valuable notes you took while following a two hours live stream for the community.

With that, I'll be a bootcamp complete wrapper.

I think. 
No I am sure. 
Nobody does it better.

Tag left up at its way to, again, track progress.
These changes are delivered to [`week-1-perfecting` branch](https://github.com/yaya2devops/terraform-beginner-bootcamp-2023/commits/47-week-one-perfecting).

- [Visibility](https://github.com/yaya2devops/terraform-beginner-bootcamp-2023/blob/47-week-one-perfecting/assets/1.9.9/README.md)

Best,
[Let's connect.](https://www.linkedin.com/in/yahya-abulhaj/)

**Notes:**
- After completing each subtask, we will resolve it and link it from here.

**Comment by yaya2devops** [comment]
I miss named the following commit https://github.com/yaya2devops/terraform-beginner-bootcamp-2023/commit/06d4d99f3f9effb195ace529308ba85fdc45b383

**Comment by yaya2devops** [comment]
But it is something that I came across a lot.

I renamed it and pushed the right one.
```
 (35-s3-static-website-host) $ $ git commit --amend -m "#47 Branch 35 Perfecting Checkmark"
(35-s3-static-website-host) $ git push --force origin 35-s3-static-website-host 
```

**Comment by yaya2devops** [comment]
The necessary content is now in good order. 
I might leave it hanging for a bit longer to gather additional inspiration..
